{% set name = "spherematch" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esheldon/smatch/archive/refs/tags/{{ version }}.tar.gz
  sha256: 3ce8e571cc9231de216852967d6c24fa2debe81a8adb3c20273dea69e8893238

build:
  number: 1
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - scipy
    - {{ pin_compatible("numpy") }}

test:
  imports:
    - smatch
    - smatch.matcher

about:
  home: https://github.com/esheldon/smatch
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: code for matching points on the sphere

extra:
  recipe-maintainers:
    - beckermr
