{% set name = "spherematch" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esheldon/smatch/archive/refs/tags/{{ version }}.tar.gz
  sha256: 690be67f7b5e6d15b782062e873add0288693c255904668226b2ea32a2b624d6

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - scipy
    - {{ pin_compatible("numpy") }}

test:
  imports:
    - smatch
    - smatch.matcher

about:
  home: https://github.com/esheldon/smatch
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: code for matching points on the sphere

extra:
  recipe-maintainers:
    - beckermr
